### ISSUE TITLE
Bug?/Feature?: Investigate the response of sheetwork on cells with limited editability (frozen)

### ISSUE THREAD

**Issue by karolinaosiak** [bastienboutonnet/sheetwork#292]
**Is your feature request related to a problem? Please describe.**
I was trying to ingest a sheet. However, after testing a few different things (including renaming the sheet), I realized I couldn't ingest the sheet unless I copy-pasted it to a new sheet. A hypothesis is that this could have be caused by the limited editability of the sheet's columns. Debugger showed empty column names were being ingested.

**Describe the solution you'd like**
1) Understand if the frozen cells were the reason of the issue
2) If yes, sheet would be ingested no matter the limited field editability (frozen cells).

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by bastienboutonnet** [comment]
Thanks for reporting this @karolinaosiak

I tried replicating the hunch we had regarding the first row being frozen but I was able to retrieve the sheet just fine. This means it's probably not an issue with this.

Just so I make sure we mean the same thing by frozen cells:
In your message you equate them to "low editability":
>If yes, sheet would be ingested no matter the limited field editability (frozen cells).

Is this a concept of yours? Frozen cells are generally editable except they just visually stay on screen when you scroll down.

I had to remove the sheet key you were trying to load because I did not want to expose to the world the sheet ID. But if you still have the sheet at hand and it still has the tab that was causing the issue would you mind DMing me the sheet info (via Slack or so?)

**Comment by bastienboutonnet** [comment]
Hi again @karolinaosiak , I was able to find the sheet you wanted to export in our codebase (the privileges you get by working on the same team haha).

I know what the issue was. The first column wasn't frozen or anything it's simply empty:
![Screenshot 2020-12-20 at 11 36 02](https://user-images.githubusercontent.com/4304794/102711144-ca92d180-42b7-11eb-994a-234ca9c10581.png)

So this will basically upset `sheetwork` as it won't be able to find a header to give a name to your columns.

When ran in `--log-level` debug, you get the following message:
```bash
2020-12-20 11:35:16,878 - Sheetwork Logger - DEBUG - load_sheet - Columns imported from sheet: ['', '', '', '', '', '', '', '']
```

I think I'll just implement a test for that (like empty strings in the first row/header. Then maybe I'll work on trying to give the user an option to specify if the header lives in a different row than expected.

I will close this comment in favour of a new issue with the todos that I just listed here.
